# Sidebar navigation

- label: "Introduction"
  link: "/"
- label: "GitHub"
  link: "https://github.com/dayhaysoos/use-shopping-cart"
- label: "Discord"
  link: "/discord"
- label: "Getting started"
  link: "/getting-started"
- label: Usage
  items:
    - label: "CartProvider"
      link: "/usage/cartprovider"
    - label: "addItem()"
      link: "/usage/addItem()"
    - label: "incrementItem()"
      link: "/usage/incrementItem()"
    - label: "decrementItem()"
      link: "/usage/decrementItem()"
    - label: "setItemQuantity()"
      link: "/usage/setItemQuantity()"
    - label: "removeItem()"
      link: "/usage/removeItem()"
    - label: "clearCart()"
      link: "/usage/clearCart()"
    - label: "redirectToCheckout()"
      link: "/usage/redirectToCheckout()"
    - label: "checkoutSingleItem()"
      link: "/usage/checkoutSingleItem()"
    - label: "validateCartItems()"
      link: "/usage/validateCartItems()"
    - label: "loadCart()"
      link: "/usage/loadCart()"
    - label: "DebugCart"
      link: "/usage/debugcart"
    - label: formatLineItems()
      link: "/usage/formatLineItems()"
    - label: "API"
      link: "/usage/api"
- label: "Contributors"
  link: "/contributors"
- label: "Util"
  items:
    - label: formatCurrencyString()
      link: "/util/formatCurrencyString()"
