# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: Usage
  items:
    - label: 'Creating docs'
      link: '/usage/creating-docs'
    - label: 'Navigation'
      link: '/usage/navigation'
    - label: 'Shadowing'
      link: '/usage/shadowing'
